module.exports = function(grunt){
  grunt.initConfig({
    htmlmin:{
      options:{
        removeComments:true,
        collapseWhitespace:true
      },
      files:{
        expand:true,
        cwd:'src',
        src:['*.html'],
        dest:'dist/'
      }
    },
    cssmin:{
      files:{
        expand:true,
        cwd:'src',
        src:['*.css'],
        dest:'dist/'
      }
    },
    uglify:{
      main:{
        files:[{
          expand:true,
          cwd:'src',
          src:['*.js'],
          dest:'dist/'
        }]
      }
    },
    copy:{
      html:{
        files:[{
          expand:true,
          cwd:'dist',
          src:['*.html'],
          dest:'src/'
        }]
      },
      js:{
        files:[{
          expand:true,
          cwd:'dist',
          src:['*.js'],
          dest:'src/'
        }]
      },
      css:{
        files:[{
          expand:true,
          cwd:'dist',
          src:['*.css'],
          dest:'src/'
        }]
      }
    }
  });

  grunt.loadNpmTasks('grunt-contrib-htmlmin');
  grunt.loadNpmTasks('grunt-contrib-cssmin');
  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.registerTask('default',['htmlmin','cssmin','uglify','copy'])
}
